### PR TITLE
Add richdem dependency

### PR DESCRIPTION
**Pull request by mcflugen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Add *richdem* as a run dependency.

### CODE REVIEW

**Comment by mcflugen** [comment]
@ocefpaf Sorry to bother you but could you help me out with this? I'm not sure how to fix these errors building *landlab* for *pypy*. Is this related to the *PyPy* 3.8+3.9 migration? Maybe we just need a new build of *richdem*?

**Comment by ocefpaf** [comment]
> @ocefpaf Sorry to bother you but could you help me out with this? I'm not sure how to fix these errors building _landlab_ for _pypy_. Is this related to the _PyPy_ 3.8+3.9 migration? Maybe we just need a new build of _richdem_?

Looks like it never got a fresh PR for pyp 3.7, see https://github.com/conda-forge/richdem-feedstock/pull/5
We will need to trigger that manually.

**Comment by mcflugen** [comment]
@ocefpaf Thanks! Since *conda-forge* has dropped support for *pypy* 3.7, should we instead trigger a build of *richdem* with 3.8 and 3.9 (and then do the same for *landlab*, I suppose)?

I've looked for instructions on how to trigger these rebuilds but I can't seem to find anything. Is this something that needs to be done by the *conda-forge* team?

**Comment by ocefpaf** [comment]
> @ocefpaf Thanks! Since _conda-forge_ has dropped support for _pypy_ 3.7, should we instead trigger a build of _richdem_ with 3.8 and 3.9 (and then do the same for _landlab_, I suppose)?

I don't think we dropped support for pypy 3.7 yet but I may be mistaken. The pypy  3.8 PRs are being issued and should reach this repo soon. If you don't care for pypy 3.7 we can merge this to "cash in" the other builds and ignore that one.

> I've looked for instructions on how to trigger these rebuilds but I can't seem to find anything. Is this something that needs to be done by the _conda-forge_ team?

We would need to add a migration file [like this one](https://github.com/conda-forge/public-wrappers-feedstock/pull/7/commits/692b6a2a328ea378305001956151a5fbaa880779) but I'd rather wait for the bot to do it. I'll check if there is something blocking it.

**Comment by mcflugen** [comment]
I found a [brief reference](https://conda-forge.org/docs/user/tipsandtricks.html#using-pypy-as-an-interpreter) in the user docs about dropping *pypy* 3.7.

We're not concerned about supporting *pypy* 3.7 so, if it's ok with you, I would like to merge this PR.

**Pull request merged**
