### PR TITLE
Add "landlab" command entry point

### PR DESCRIPTION
**Pull request by mwtoews**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

---

With a fresh install of landlab 2.7.0 on Windows, the `landlab` command does not work:
```
C:\> mamba create -n landlab landlab
...
C:\> mamba activate landlab
(landlab) C:\> landlab
Fatal error in launcher: Unable to create process using '"D:\bld\landlab_1699164910624\_h_env\python.exe"  "C:\Users\username\AppData\Local\miniforge3\envs\landlab\Scripts\landlab.exe" ': The system cannot find the file specified.
```
This command should not have any issues, as it can be run manually:
```
> python -c "from landlab.cmd import landlab; landlab.landlab()" --help

 Usage: -c [OPTIONS] COMMAND [ARGS]...

...
```

This PR resolves the issue by specifying [Python entry points](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#python-entry-points) in the recipe.

### CODE REVIEW

**Comment by mwtoews** [comment]
@conda-forge-admin, please rerender

**Comment by mwtoews** [comment]
@conda-forge-admin, please rerender

**Comment by mwtoews** [comment]
It seems the sha256 changed for a single release. I find GitHub-related API to sometimes generate dynamic outputs that may change their checksums. A more reliable source is to switch to PyPI, which has a static sdist. The [history for landlab](https://pypi.org/project/landlab/#history) looks pretty good an complete, so this would be a better place to set the source.

**Comment by mcflugen** [comment]
@mwtoews Ugh. I'm sorry, I had forgotten about this pull request. I've incorporated your changes in #56.

**Pull request closed without merging**
