### PR TITLE
TST: Add pip check to tests and missing dependency

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adding netcfd4 because this package is listed in the requirements upstream. Also adding pip check to tests so other dependencies are not missed in the future.

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
pypy build is trying to install cypython packages?

```
The reported errors are:
- Encountered problems while solving:
-   - package richdem-2.3.0-py37h1c464ab_0 requires python >=3.7,<3.8.0a0 *_cpython, but none of the providers can be installed
```

**Comment by carterbox** [comment]
All pypy builds fail because of ongoing issues with richdem; not because of this PR.

https://github.com/conda-forge/landlab-feedstock/pull/45#issuecomment-1106534191

**Comment by mcflugen** [comment]
Looks good. Thanks @carterbox!

**Pull request merged**
